### ISSUE TITLE
配置devtool: 'source-map'没有生效

### ISSUE THREAD

**Issue by zhugexiansheng** [easy-team/easywebpack-js#1]
配置了devtool: 'source-map'在运行easy build prod --devtool source-map没有生成对应的.map文件
![image](https://user-images.githubusercontent.com/13861291/64397279-55d05f80-d093-11e9-8f5f-0c92015ff1b7.png)

**Comment by hubcarl** [comment]
@zhugexiansheng 
![image](https://user-images.githubusercontent.com/4983042/64471259-f3a25800-d181-11e9-9dd9-dd52e60148c3.png)

https://www.yuque.com/easy-team/easywebpack/base

**Comment by hubcarl** [comment]
![image](https://user-images.githubusercontent.com/4983042/64471338-15500f00-d183-11e9-9525-65c713c5141a.png)

看一下 easywebpack-cli 和  easywebpack-js 版本，请安装 4.x.x 最新版本
